# Generated by Django 6.0.6 on 2026-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReg',
            fields=[
                ('slno', models.IntegerField(db_column='Slno')),
                ('donorid', models.CharField(db_column='Donorid', max_length=50, primary_key=True, serialize=False)),
                ('dname', models.CharField(blank=True, db_column='Dname', max_length=100, null=True)),
                ('dpsd', models.CharField(db_column='Dpsd', max_length=255)),
                ('dcpsd', models.CharField(db_column='Dcpsd', max_length=255)),
                ('dob', models.DateField(blank=True, db_column='Dob', null=True)),
                ('gen', models.CharField(blank=True, db_column='Gen', max_length=20, null=True)),
                ('dmob', models.CharField(blank=True, db_column='Dmob', max_length=15, null=True)),
                ('demail', models.CharField(blank=True, db_column='Demail', max_length=100, null=True)),
                ('add1', models.CharField(blank=True, db_column='Add1', max_length=100, null=True)),
                ('add2', models.CharField(blank=True, db_column='Add2', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('pin', models.CharField(blank=True, db_column='Pin', max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
                ('userrole', models.CharField(blank=True, db_column='UserRole', default='donor', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'db_table': 'donorreg',
                'ordering': ['slno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnusedThing',
            fields=[
                ('slno', models.IntegerField(db_column='Slno')),
                ('proid', models.CharField(db_column='Proid', max_length=50, primary_key=True, serialize=False)),
                ('proname', models.CharField(blank=True, db_column='ProName', max_length=100, null=True)),
                ('procate', models.CharField(blank=True, db_column='ProCate', max_length=100, null=True)),
                ('prosubcate', models.CharField(blank=True, db_column='ProSubCate', max_length=100, null=True)),
                ('proserial', models.CharField(blank=True, db_column='ProSerial', max_length=100, null=True)),
                ('probatchno', models.CharField(blank=True, db_column='ProBatchno', max_length=100, null=True)),
                ('purchdate', models.DateField(blank=True, db_column='PurchDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
                ('donorid', models.CharField(blank=True, db_column='Donorid', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Unused Thing / Donation',
                'verbose_name_plural': 'Unused Things / Donations',
                'db_table': 'unusedthing',
                'ordering': ['-purchdate', 'slno'],
                'managed': False,
            },
        ),
    ]
