# Generated by Django 6.0.6 on 2026-09-14 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTable',
            fields=[
                ('slno', models.IntegerField(db_column='Slno')),
                ('proid', models.CharField(db_column='Proid', max_length=50, primary_key=True, serialize=False)),
                ('collqty', models.CharField(blank=True, db_column='CollQty', max_length=10, null=True)),
                ('recdate', models.DateField(blank=True, db_column='RecDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('donby', models.CharField(blank=True, db_column='DonBy', max_length=100, null=True)),
                ('donoradd', models.CharField(blank=True, db_column='DonorAdd', max_length=200, null=True)),
                ('recby', models.CharField(blank=True, db_column='RecBy', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Collection Detail',
                'verbose_name_plural': 'Collection Details',
                'db_table': 'collectiontable',
                'ordering': ['-recdate', 'slno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistributeTable',
            fields=[
                ('slno', models.IntegerField(db_column='Slno')),
                ('proid', models.CharField(db_column='Proid', max_length=50, primary_key=True, serialize=False)),
                ('disqty', models.CharField(blank=True, db_column='DisQty', max_length=10, null=True)),
                ('disdate', models.DateField(blank=True, db_column='DisDate', null=True)),
                ('disby', models.CharField(blank=True, db_column='DisBy', max_length=100, null=True)),
                ('recname', models.CharField(blank=True, db_column='RecName', max_length=100, null=True)),
                ('recadd', models.CharField(blank=True, db_column='RecAdd', max_length=200, null=True)),
                ('recmob', models.CharField(blank=True, db_column='RecMob', max_length=15, null=True)),
                ('recby', models.CharField(blank=True, db_column='RecBy', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Distribution Detail',
                'verbose_name_plural': 'Distribution Details',
                'db_table': 'distributetable',
                'ordering': ['-disdate', 'slno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('slno', models.IntegerField(db_column='Slno')),
                ('proid', models.CharField(db_column='Proid', max_length=50, primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, db_column='Pname', max_length=100, null=True)),
                ('cate', models.CharField(blank=True, db_column='Cate', max_length=100, null=True)),
                ('subcate', models.CharField(blank=True, db_column='SubCate', max_length=100, null=True)),
                ('proslno', models.CharField(blank=True, db_column='ProSlno', max_length=100, null=True)),
                ('batchno', models.CharField(blank=True, db_column='BatchNo', max_length=100, null=True)),
                ('disamt', models.CharField(blank=True, db_column='DisAmt', max_length=30, null=True)),
                ('stockamt', models.CharField(blank=True, db_column='StockAmt', max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Stock Detail',
                'verbose_name_plural': 'Stock Details',
                'db_table': 'stockdetails',
                'ordering': ['slno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('slno', models.IntegerField(blank=True, db_column='Slno', null=True)),
                ('recipient_id', models.CharField(db_column='Recipientid', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('mobile', models.CharField(db_column='Mobile', max_length=20)),
                ('address', models.CharField(db_column='Address', max_length=200)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('state', models.CharField(db_column='State', max_length=50)),
                ('pin', models.CharField(blank=True, db_column='Pin', max_length=10, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
                ('userrole', models.CharField(db_column='UserRole', default='recipient', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True, db_column='DateJoined')),
            ],
            options={
                'verbose_name': 'Recipient / Needy Person',
                'verbose_name_plural': 'Recipients / Needy Persons',
                'db_table': 'recipient',
                'ordering': ['recipient_id'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('req_id', models.CharField(db_column='ReqId', max_length=50, primary_key=True, serialize=False)),
                ('req_date', models.DateField(auto_now_add=True, db_column='ReqDate')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Distributed', 'Distributed')], db_column='Status', default='Pending', max_length=30)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=200, null=True)),
                ('item', models.ForeignKey(db_column='Proid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='RegApp.unusedthing')),
                ('recipient', models.ForeignKey(db_column='Recipientid', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='DetailApp.recipient')),
            ],
            options={
                'verbose_name': 'Donation Request',
                'verbose_name_plural': 'Donation Requests',
                'db_table': 'donationrequest',
                'ordering': ['-req_date', 'req_id'],
            },
        ),
    ]
